version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18  
  pre_build:
    commands:
      - npm install
  build:
    commands:
  post_build:
    commands:
artifacts:
  files:
    - server.js
    - index.html
    - package.json
    - node_modules/*
    - json/*
    - js/*
    - images/*
    - html/*
    - appspec.yml
    - scripts/**/*
    - styles/*
    - html/admin/*
  discard-paths: no

cache:
  paths:
    - 'frontend/node_modules/**/*'